In [19]:
import nashpy as nash
import numpy as np

# 定义两个玩家的收益矩阵
payoff_matrix1 = np.array([[[1, -1], [-2, 2], [0, 0]],
                          [[0, 0], [1, -1], [-1, 1]],
                          [[-1, 1], [2, -2], [1, -1]]])

payoff_matrix2 = np.array([[[2, -2], [-1, 1], [-3, 3]],
                           [[-2, 2], [3, -3], [1, -1]],
                           [[-1, 1], [-3, 3], [2, -2]]])

payoff_matrix3 = np.array([[[2, 4], [1, 1], [5, 1]],
                           [[0, 0], [4, 0], [1, 5]],
                           [[4, 1], [3, 3], [2, 2]]])

payoff_matrix4 = np.array([[[0.5, 0.5], [0.0, 1.0], [1.0, 0.0]],
                           [[1.0, 0.0], [0.5, 0.5], [0.0, 1.0]],
                           [[0.0, 1.0], [1.0, 0.0], [0.5, 0.5]]])  # Rock-Paper-Scissors

row_payoff_matrix = payoff_matrix2[:, :, 0]
column_payoff_matrix = payoff_matrix2[:, :, 1]

# 创建一个双人博弈
game = nash.Game(row_payoff_matrix, column_payoff_matrix)

# 计算所有混合策略纳什均衡
equilibria = game.support_enumeration()

# 输出博弈矩阵
print("Game:")
print(game)

# 计算并输出行玩家和列玩家的收益
for eq in equilibria:
    row_strategy, col_strategy = eq
    row_payoff = row_strategy @ row_payoff_matrix @ col_strategy
    col_payoff = row_strategy @ column_payoff_matrix @ col_strategy

    print(f"\nEquilibrium strategies:\nRow player: {row_strategy}\nColumn player: {col_strategy}")
    print(f"Expected payoff for Row player: {row_payoff}")
    print(f"Expected payoff for Column player: {col_payoff}")


Game:
Zero sum game with payoff matrices:

Row player:
[[ 2 -1 -3]
 [-2  3  1]
 [-1 -3  2]]

Column player:
[[-2  1  3]
 [ 2 -3 -1]
 [ 1  3 -2]]

Equilibrium strategies:
Row player: [0.375      0.33928571 0.28571429]
Column player: [0.5        0.14285714 0.35714286]
Expected payoff for Row player: -0.2142857142857143
Expected payoff for Column player: 0.2142857142857143
